name: CI

on:
  push:
    branches: [ dockerize, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t myapp .

    - name: Test
      run: docker run myapp npm run test
